### ISSUE TITLE
Addresses probably off (mega issue thread)

### ISSUE THREAD

**Issue by ddthj** [drssoccer55/RLBot#1] opened 2017-04-06 02:16 UTC
Since rocket league has updated several times I'm pretty sure the addresses for most variables have changed.

When attempting to train I would the error:
"OverflowError Python int too large for c Long"
when trying to read the z axis height of the ball and another variable

I verified in cheatengine that the current address for the ball z height no longer existed, or maybe I mistyped the offset.

Would love if you kept this updated, I wrote a mod for xbox.py so that I can take regular keyboard inputs again for training since I play on a keyboard.

**Comment by drssoccer55** [comment] 2017-05-09 05:00
Sorry I am just seeing this now.  This game frequently updating is problematic and definitely the cause of issues.  That might be another issue you are getting though because generally it will just read from an illegal location or return a value from a random part of memory that you wouldn't want.  Obtaining all the cheat engine values after an update is tedious.  I am trying to take the lessons learned from this project and apply them to another project.  Possibly a game which is not regularly updated.

I appreciate you trying out the project though even though it is not in a maintained shape! I believe I did try to add a warning about that in the readme but this project will not work out-of-the-box unless you revert your rocket league version, and even then I have only verified it on my machine so there could be other problems.

**Comment by ddthj** [comment] 2017-05-11 04:38
Yea I figured that the program was probably reading something from an illegal location. I tried to use cheat engine to find the new addresses but didn't have any luck (I really didn't know what I was doing haha).

Still a neat project, I'd like to work on it more in the future.

**Comment by drssoccer55** [comment] 2017-05-12 03:12
I have some cheat engine tips since I learned it for this project.  The first thing I would recommend is finding the value for boost.  This is the easiest because you know the exact numerical value and it is very easy to change. So in cheat engine you open up the exe and you want to scan for the 4 byte value equal to the boost as the first scan. Then in the game you can either pick up boost or use it to change the value and scan again. It keeps narrowing down. Eventually you will get it narrowed down to like 6 values which all seem to correspond to boost. Of those 6 values there is only one that you actually want though. The trick to finding which one you want is make sure you have 0 boost and use cheat engine to alter one of the values to 100.  Then go in game and run over one of the small boost pickups and watch the boost value.  If the value jumps up 100 for a fraction of a second before resetting that is the memory location you want! Once you have that memory location you right click on the memory location and do a "pointer scan for this address." Default settings are probably fine. This scan will save a file and it will be a large file.  Now close out of the game and open it up again and repeat but this time when you do the pointer scan use the file from before.  When you keep repeatedly doing this the pointer trails keep narrowing until you have a few left.  You might still have a few hundred pointer paths after a few repeats of this technique but usually that is okay. Here is an example of me having the ball z address narrowed down to 2 pointers and you can see I used one of the pointers in my code.

![image](https://cloud.githubusercontent.com/assets/23265878/25980549/1a2968ce-3684-11e7-881e-575d37459f4f.png)

Some other tips:
- All values are floats except boost and scoreboard values.
- When finding the z position of yourself, the bot, or the ball. Pause the game. This value is still in memory and it makes it a lot easier :)
- I only use cheat engine to find 8 different memory locations and the others are calculated from the offsets of those locations. Save yourself some time and look at PlayHelper.py for the 8 ones. Just use cheat engine to look at the memory location 4 bytes away or so if you want to check these.
- If you find the right z coordinate you can edit it to teleport yourself, the bot, or the ball around and you will know you have the right one. The teleport will only happen when you resume the game though,
- This does take some time to do.  If you have any questions just ask,
- When I say score I mean like the number of goals scored and when I say "score" I mean the value that is like 10 points for first touch etc score.

**Comment by ddthj** [comment] 2017-08-15 03:11
So I've gotten around to playing with this again, after 14 pointer rescans I'm still getting about 3,000 results for boost, do you know any other way to rescan that doesn't get so many results? I may just pick pointers at random and keep using them until they break...

**Comment by drssoccer55** [comment] 2017-08-15 05:39
Honestly boost is the most frustrating to find in my experience  You might already know some of these things but a few things I have found are:

- Closing and reopening rocket league helps eliminate more than just doing a game restart 
- Specifically for boost I get 5 possible values, 3 of which I can edit and they stay fixed at the edit value, I use one of the remaining 2 values where if I edit it all 5 values reset.  (Boost seems like the only value in the game they have cheat protection on).
- I like to sort the pointers by size and use the smallest ones
- I do the pick pointers until they break too
- 14 rescans is a more than I've had to do I think 7 is like my max.

**Comment by ddthj** [comment] 2017-08-15 17:45
Thanks for the quick response! Yea I think I might just grab a bunch of pointers and have code use whichever ones still point to values between 0 and 100 haha. One question - what are all the player and bot rot#s? like 1-9, are they all rotations about the axes and do you know what axes they are?

I also had an idea for the bot that would probably make it a much better player. I'm going to try and hardcode most of the 'tasks' in rocket league such as intercepting/hitting the ball, planning intercepts (like ensuring that the car can always reach the ball before the ball is scored), and boost pickup, then use AI to decide which 'task' would be most important to execute given the current values in the game.

Since this differs too much from your original code I think my first step will just be to write a ghetto ingame API like your sendkeys and rwm/playhelper files, I'll probably have more questions about those in the future :).

**Comment by ddthj** [comment] 2017-08-15 19:26
Oh I just realized you are thinking about bot tournaments! Count me in!

**Comment by drssoccer55** [comment] 2017-08-15 20:43
Aw yeah!  I have a tournament rules document which I am working on which you can check out https://docs.google.com/document/d/1-T4qgDqXyCLYhpqNaSKPqpzJ7dmgeeIG0ZUny20zhw0/edit?usp=sharing.  In the document I describe what I know about the rotation variables.  I don't know what the 9 rotations actually represent but I know some properties of it.  Also I have my example AlwaysTowardsAgent.py code where I use some of the rotation values.  If you figure out the what the rotations actually represent that would be fantastic to let me know.  I was just looking through the memory and they all seemed unique and useful.

**Comment by ddthj** [comment] 2017-08-18 00:35
Can you write out how to set up the "dev environment," I'd like to be able to test my bot in a match like you created in the video with two custom bots against eachother. Also, do the address pointers vary by computer? it'd be nice if we could all share working pointers to make things easier.

**Comment by drssoccer55** [comment] 2017-08-18 03:21
I just did a quick test and pointers do work between computers!  I was able to copy the pointer trail I got from my desktop and use it on my laptop successfully and it appeared all pointers were working with the current pointers in playhelper.py!  The only one I couldn't check for sure was orange boost because I was running against the bot instead of player vs player.

**Comment by drssoccer55** [comment] 2017-08-18 03:45
Alright this is good news.  Let's get this working on your desktop.  Try these next few steps and we should be good to go.

1. Install vjoy: http://vjoystick.sourceforge.net/site/index.php/download-a-install/how-to-install
2. I followed these install instructions for pyvjoy: https://github.com/tidzo/pyvjoy/issues/7
3. Install x360ce: https://gamerinfo.net/game/rocket-league/x360ce/
4. Open configreVjoy (installed with vjoy) and make sure 1 and 2 are green. I never touched these settings but you can match mine if you want.
![image](https://user-images.githubusercontent.com/23265878/29443291-ef3c0e46-838b-11e7-997d-92d7edac37e9.png)
5. A quick test you can run.  Open "vjoy Device List".  At first it should look like this: 
![image](https://user-images.githubusercontent.com/23265878/29443330-36a1ee40-838c-11e7-84a5-773f2fb630f2.png)

Now keep it open and simultaneously run python p2join.py (all this does is press the start button or a button for a second and release it)  While this is running you should see a pid appear for player 2:
![image](https://user-images.githubusercontent.com/23265878/29443372-750df0c0-838c-11e7-8fb7-4da80454f1ae.png)

6. Run x360ce.exe from your rocket league binary directory as an administrator.  Here is what my screen looks like with 2 vjoy devices (I never touched any settings besides letting it autofill in fields for a vjoy controller): 
![image](https://user-images.githubusercontent.com/23265878/29443425-bbe65370-838c-11e7-9b00-9887b677312f.png)

You might want to run "python resetDevices" to make sure there are 2 vjoy controllers.

7. Run python runner.py while the game is running.  You can pause the game and minimize it and run it no problem just t see the window appear.  When I make my videos I use OBS to overlay the window on top of the game.

**Comment by drssoccer55** [comment] 2017-08-18 03:54
Oh and another thing.  I use p2join.py to press start initially so the controller joins in.  I also edit it to press the "a" button to autojoin in.  For 1st player you can just use keyboard to set it up. To change it just set p2.data.lButtons = 1 for "A" and p2.data.lButtons = 128 for "Start".  I'll separate these scripts and make more for each thing I want to do probably.

The reason for these numbers is that it is 2^(button# - 1) as seen in the picture above.  (Ex. A Button = Button 1 so 2^(1-1) = 2^0 =1 .... Y Button = Button 4 so (2^3) = 8 would be Y button.  To press simultaneously just add them.

**Comment by ddthj** [comment] 2017-08-18 04:44
Awesome! I'll try this out tomorrow, I was worried the only way to test my bot would be in a freeplay mode but with 2 custom bots I can just have one doing nothing.

**Comment by ddthj** [comment] 2017-08-18 17:56
![](https://i.gyazo.com/845df94114a07fe687f55f5422c0cd5b.png)

Not sure if this is supposed to happen, but it appears to be working

**Comment by ddthj** [comment] 2017-08-18 19:06
Can you make a video of your process to start a match between 2 bots? I've got all the software I just can't figure out how to get this all set up properly

**Comment by drssoccer55** [comment] 2017-08-18 19:55
Yeah I can try to do that tonight or tomorrow if I have time.  Can you get p2 to join in?  I usually have rocket league at the menu screen, minimize it out, run p2join.py, and quicky go back into the game.  (The script waits a few second than does the button press).  I think it can only send controller presses to the active window.  It's not ideal but it works.

**Comment by ddthj** [comment] 2017-08-18 21:06
I haven't been able to get p2 to join, I'm still not sure if it's because of the error or not since it does appear in the vjoy device list. I tried running it from an admin command prompt too with the same error

**Comment by drssoccer55** [comment] 2017-08-18 21:32
Hmm the issue is definitely coming from pyvjoy since p2join.py only uses that library.  Couple of other people have seen this too: https://github.com/tidzo/pyvjoy/issues/1

Pretty sure I used the 64 version of vjoy 1.X off the op of my head. You might want to try a different vjoy install.

**Comment by ddthj** [comment] 2017-08-19 00:43
I had installed version 2.1.8 since it was the recommended, how do you install 1.x? I tried using the executable and I just get a 'failed to install' error in the wizard

**Comment by drssoccer55** [comment] 2017-08-19 01:07
Ah sorry just got back at my computer and I have 2.1.8.

**Comment by drssoccer55** [comment] 2017-08-19 01:35
I can't replicate this :/

Can you do set_button instead of update?  You can just run a few lines from their readme in the interpreter https://github.com/tidzo/pyvjoy/blob/master/README

**Comment by ddthj** [comment] 2017-08-19 01:48
set_button doesn't throw any errors but I still can't get anything to happen in the game, I need to know the order of running everything (like do I run p2join in the choose team menu and when do I start runner.py?)
think you could add me on steam? -> GooseFairy

**Comment by drssoccer55** [comment] 2017-08-19 02:33
For posterity. We were able to get around the issue by using set_button in place of update.  Update is more efficient and ideal though so hopefully a fix is found for the OSError issue.

**Comment by ddthj** [comment] 2017-08-20 00:52
are all your libraries 32bit or 64bit? I just realized that I'm using 32bit python (on a 64bit machine) and you're using 64bit

**Comment by drssoccer55** [comment] 2017-08-20 02:39
I use 64 bit for everything where possible when given the choice so yeah likely everything is 64 bit!

**Comment by hinnerkoetting** [comment] 2017-08-20 10:43
I had the same issue using some 32 bit versions but switching to 64 bit versions seems to fix it.
It seems like you have to use 64 bit python and the 64 bit version of vJoyInterface.dll.

**Comment by hinnerkoetting** [comment] 2017-08-20 11:53
I tried to use the AlwaysTowardBallAgents and they are just driving in circles I guess because the ball position cannot be read from memory.
It seems to me that the memory addresses are somehow dependent on the gamemode and number of players. When starting the game in Training - free play values read from memory are 0. When starting a private game with me as spectator and two "Agents" all values are at least != 0 but the ball position changes all the time although the ball is not moving.
Could you describe the exact game setup that you used?

**Comment by mmendesc** [comment] 2017-11-08 03:27
Trying to set up project but I got the same error on updateVJD, OSError: exception: access violation writing 0x0000002.

I was able to set manually the player2 start button in the python interpreter using set_button. 

Did you guys solved this?

**Comment by tarehart** [comment] 2017-11-08 04:03
That's a known error message covered in https://github.com/drssoccer55/RLBot/wiki/Setup-Instructions near the bottom. Are you using 64 bit python?

**Comment by mmendesc** [comment] 2017-11-08 14:52
Thanks @tarehart, my mistake I tought I had installed the 64bit version. Replaced the python and now everything is working.

**Comment by drssoccer55** [comment] 2017-11-12 23:18
Closing for v3.

**Closed by drssoccer55** 2017-11-12 23:18 UTC
